### ISSUE TITLE
Remove all the documentation related to the MyST book theme

### ISSUE THREAD

**Issue by InessaPawson** [possee-org/sklearn-survey-report-2024#1]

**Comment by Auslum** [comment]
Done, I removed all the documentation that is not related to the current project.

**Comment by InessaPawson** [comment]
@Auslum Please submit a PR to https://github.com/possee-org/sklearn-survey-report-2024 to resolve this issue.

**Comment by Auslum** [comment]
Done, I submitted the PR.
